name: Compiler Tests
run-name: Automated - Run Nightly Compiler Tests
#  allows us to repeat this daily at 2am
#  https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
on:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  Test-gem5art:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 1440 # 24 hours
    # *********** why do we use a docker image here normally. it works fine w/o one i think ****************************

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # For this, should probably go in kokoro tests files?
      - name: Run Pre Commit Tests
        run: |
          PRE_COMMIT_HOME=/tmp/pre-commit-cache pre-commit run --from-ref HEAD~ --to-ref HEAD
          cd tests
          ./main.py run -j4 -t4 gem5 -vv && scons -C .. --no-compress-debug --ignore-style build/ARM/unittests.opt

      - name: Run Compiler Tests
        run: |
          chmod u+x compiler-tests.sh
          ./compiler-tests.sh -j $(nproc)

      - run: echo "🍏 This job's status is ${{ job.status }}."
